@id=974cd330-67f8-49ea-bf51-7a39a5b8c530

PUT https://localhost:7137/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}
